<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>NRED1._0.Business</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
 

  <ItemGroup>
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
    <PackageReference Include="System.Net.Primitives" Version="4.3.0" />
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="DinkToPdfIncludesDependencies" Version="1.0.8" />
    <PackageReference Include="Handlebars.Net" Version="2.1.4" />
    <PackageReference Include="Handlebars.Net.Extension.NewtonsoftJson" Version="1.0.3" />
    <PackageReference Include="Handlebars.Net.Helpers.Json" Version="2.4.1.5" />
    <PackageReference Include="HtmlToPdfConverter.Core" Version="2.0.0" />
    <PackageReference Include="LibWkHtmlToX-32" Version="0.12.6.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="7.0.1" />
    <PackageReference Include="QRCoder" Version="1.4.2" />
    <PackageReference Include="Serilog" Version="3.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.22.0" />
    <PackageReference Include="Wkhtmltopdf.NetCore" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Capex.DomainModels\Capex.DomainModels.csproj" />
    <ProjectReference Include="..\Capex.Infrastructure\Capex.Infrastructure.csproj" />
    <ProjectReference Include="..\Capex.Models\Capex.Models.csproj" />
    <ProjectReference Include="..\Capex.Utilities\Capex.Utilities.csproj" />
  </ItemGroup>

</Project>
