//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capex.Utilities.Resource.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_hi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_hi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capex.Utilities.Resource.ErrorMessages.ErrorMessages_hi", typeof(ErrorMessages_hi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मैं एतद्द्वारा घोषणा करता हूं कि मुझे समग्र पोर्टल पर उस आधार आधारित प्रमाणीकरण प्रणाली के साथ खुद को प्रमाणित करना होगा और आधार आधारित प्रमाणीकरण के बाद अपना आधार नंबर, बायोमेट्रिक, और/या वन-टाइम पिन (ओटीपी) डेटा प्रदान करना होगा। सहमति देने में कोई आपत्ति नहीं है. मैं इस बात से भी सहमत हूं कि समग्र सामाजिक सुरक्षा मिशन मेरी पहचान स्थापित करने और प्रमाणित करने के लिए मेरे आधार नंबर का उपयोग कर सकता है। मैं केवल सरकारी लाभ प्राप्त करने के उद्देश्य से अपने आधार और के-वाई-सी विवरण को अन्य राज्य और केंद्र सरका [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdharDisclosure {
            get {
                return ResourceManager.GetString("AdharDisclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सफलतापूर्वक.
        /// </summary>
        internal static string Err00000 {
            get {
                return ResourceManager.GetString("Err00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुछ तकनीकी समस्या है! कृपा पुनः कोशिश करें!.
        /// </summary>
        internal static string Err00001 {
            get {
                return ResourceManager.GetString("Err00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अवैध पासवर्ड।.
        /// </summary>
        internal static string Err00002 {
            get {
                return ResourceManager.GetString("Err00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अवैध मोबाइल नंबर।.
        /// </summary>
        internal static string Err00003 {
            get {
                return ResourceManager.GetString("Err00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नया पासवर्ड और कन्फर्म पासवर्ड मैच नहीं हुआ।.
        /// </summary>
        internal static string Err00004 {
            get {
                return ResourceManager.GetString("Err00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पुराना पासवर्ड और नया पासवर्ड एक जैसा नहीं होना चाहिए।.
        /// </summary>
        internal static string Err00005 {
            get {
                return ResourceManager.GetString("Err00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पुराना पासवर्ड मैच नहीं किया।.
        /// </summary>
        internal static string Err00006 {
            get {
                return ResourceManager.GetString("Err00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नए पासवर्ड को पुराने पासवर्ड से सेम नहीं होना चाहिए।.
        /// </summary>
        internal static string Err00007 {
            get {
                return ResourceManager.GetString("Err00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिकॉर्ड अपडेटेड सफलतापूर्वक।.
        /// </summary>
        internal static string Err00008 {
            get {
                return ResourceManager.GetString("Err00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिकॉर्ड सेव सफलतापूर्वक।.
        /// </summary>
        internal static string Err00009 {
            get {
                return ResourceManager.GetString("Err00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अवैध यूजर आई.डी और पासवर्ड।.
        /// </summary>
        internal static string Err00010 {
            get {
                return ResourceManager.GetString("Err00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोल नाम पहले से मौजूद है।.
        /// </summary>
        internal static string Err00011 {
            get {
                return ResourceManager.GetString("Err00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोल और मेनू अनुमति सेव सफलतापूर्वक।.
        /// </summary>
        internal static string Err00012 {
            get {
                return ResourceManager.GetString("Err00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोल और मेनू अनुमति अपडेटेड सफलतापूर्वक।.
        /// </summary>
        internal static string Err00013 {
            get {
                return ResourceManager.GetString("Err00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुछ गलत हुआ।.
        /// </summary>
        internal static string Err00014 {
            get {
                return ResourceManager.GetString("Err00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोल नाम पहले से ही एक्टिवेट ऑर डीएक्टिवेट रिकार्ड्स में मौजूद है।.
        /// </summary>
        internal static string Err00015 {
            get {
                return ResourceManager.GetString("Err00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ओटीपी सफलतापूर्वक भेज दिया गया है।.
        /// </summary>
        internal static string Err00016 {
            get {
                return ResourceManager.GetString("Err00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आप सफलतापूर्वक लॉगिन हो चुके है।.
        /// </summary>
        internal static string Err00017 {
            get {
                return ResourceManager.GetString("Err00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिकॉर्ड डीएक्टिवेट सफलतापूर्वक हो चूका है।.
        /// </summary>
        internal static string Err00018 {
            get {
                return ResourceManager.GetString("Err00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अवैध यूजर आई.डी।.
        /// </summary>
        internal static string Err00020 {
            get {
                return ResourceManager.GetString("Err00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोल सफलतापूर्वक निष्क्रिय कर दिया गया है |.
        /// </summary>
        internal static string Err00021 {
            get {
                return ResourceManager.GetString("Err00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोल एक्टिवेट सफलतापूर्वक हो चूका है।.
        /// </summary>
        internal static string Err00022 {
            get {
                return ResourceManager.GetString("Err00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to असमर्थ हूँ। कैप्चा लोड करने के लिए।.
        /// </summary>
        internal static string Err00023 {
            get {
                return ResourceManager.GetString("Err00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कैप्चा वेलिडेशन सफलतापूर्वक हो चूका है।.
        /// </summary>
        internal static string Err00024 {
            get {
                return ResourceManager.GetString("Err00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कैप्चा वेलिडेशन फेल्ड।.
        /// </summary>
        internal static string Err00025 {
            get {
                return ResourceManager.GetString("Err00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ओटीपी सत्यापन फेल्ड।.
        /// </summary>
        internal static string Err00026 {
            get {
                return ResourceManager.GetString("Err00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यूजर आई.डी पहले से ही रिकॉर्ड में एक्टिवेट है।.
        /// </summary>
        internal static string Err00027 {
            get {
                return ResourceManager.GetString("Err00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to समग्र आई.डी सफलतापूर्वक ऑथेंटिकेट हो चूका है।.
        /// </summary>
        internal static string Err00028 {
            get {
                return ResourceManager.GetString("Err00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यूजर सफलतापूर्वक रजिस्टर्ड हो चूका है। यूजर आईडी और पासवर्ड आपके ईमेल/मोबाइल पर भेज दिया गया है.
        /// </summary>
        internal static string Err00029 {
            get {
                return ResourceManager.GetString("Err00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to समग्र डाटा प्राप्त नहीं हुआ।.
        /// </summary>
        internal static string Err00030 {
            get {
                return ResourceManager.GetString("Err00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ऑफिस सेव  सफलतापूर्वक हुआ।.
        /// </summary>
        internal static string Err00031 {
            get {
                return ResourceManager.GetString("Err00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ऑफिस अपडेट सफलतापूर्वक हुआ।.
        /// </summary>
        internal static string Err00032 {
            get {
                return ResourceManager.GetString("Err00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ऑफिस नाम रिकार्ड्स में मौजूद है।.
        /// </summary>
        internal static string Err00033 {
            get {
                return ResourceManager.GetString("Err00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यूजर ईमेल आई.डी पहले से ही दर्ज है।, कृपा दुसरा ईमेल आई.डी प्रदान करें ।.
        /// </summary>
        internal static string Err00034 {
            get {
                return ResourceManager.GetString("Err00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to फ़ाइल अपलोड असफलतापूर्वक हुई !.
        /// </summary>
        internal static string Err00035 {
            get {
                return ResourceManager.GetString("Err00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to फ़ाइल सफलतापूर्वक अपलोड हुई !.
        /// </summary>
        internal static string Err00036 {
            get {
                return ResourceManager.GetString("Err00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ईमेल आई.डी और कर्मचारी कोड पहले से ही दर्ज है।.
        /// </summary>
        internal static string Err00038 {
            get {
                return ResourceManager.GetString("Err00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्मचारी सफलतापूर्वक शामिल हो गया है।.
        /// </summary>
        internal static string Err00039 {
            get {
                return ResourceManager.GetString("Err00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिकॉर्ड प्राप्त नहीं हुआ।.
        /// </summary>
        internal static string Err00040 {
            get {
                return ResourceManager.GetString("Err00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पासवर्ड परिवर्तन सफलतापूर्वक हुआ।.
        /// </summary>
        internal static string Err00041 {
            get {
                return ResourceManager.GetString("Err00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जूरिस्डिक्शन सफलतापूर्वक सेव हुआ।.
        /// </summary>
        internal static string Err00042 {
            get {
                return ResourceManager.GetString("Err00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जूरिस्डिक्शन सेव सफलतापूर्वक हुआ।.
        /// </summary>
        internal static string Err00043 {
            get {
                return ResourceManager.GetString("Err00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यूजर पहले से ही दर्ज है।.
        /// </summary>
        internal static string Err00044 {
            get {
                return ResourceManager.GetString("Err00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाइल नंबर पहले से ही दर्ज है।.
        /// </summary>
        internal static string Err00045 {
            get {
                return ResourceManager.GetString("Err00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जूरिस्डिक्शन अपडेट सफलतापूर्वक हुआ।.
        /// </summary>
        internal static string Err00046 {
            get {
                return ResourceManager.GetString("Err00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिकॉर्ड डीएक्टिवेट सफलतापूर्वक हुआ।.
        /// </summary>
        internal static string Err00047 {
            get {
                return ResourceManager.GetString("Err00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आप का ई-के.वाई.सी अपडेट नहीं है। कृपा आप समग्र पोर्टल पर आपने ई-के.वाई.सी अपडेट करें । फिर उसके बाद अपना एकाउंट क्रिएट करें ।.
        /// </summary>
        internal static string Err00048 {
            get {
                return ResourceManager.GetString("Err00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाइल नंबर समग्र पोर्टल पर अपडेट नहीं है।.
        /// </summary>
        internal static string Err00049 {
            get {
                return ResourceManager.GetString("Err00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यूजर रजिस्टर  सफलतापूर्वक हुआ। यूजर आईडी और पासवर्ड आपके ईमेल/मोबाइल पर भेज दिया गया है.
        /// </summary>
        internal static string Err00050 {
            get {
                return ResourceManager.GetString("Err00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एन-आर-ई  विवरण अपडेट  सफलतापूर्वक हुआ।.
        /// </summary>
        internal static string Err00051 {
            get {
                return ResourceManager.GetString("Err00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ओटीपी सत्यापित सफलतापूर्वक हुआ।.
        /// </summary>
        internal static string Err00052 {
            get {
                return ResourceManager.GetString("Err00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपा वैध ओटीपी दर्ज करें।.
        /// </summary>
        internal static string Err00053 {
            get {
                return ResourceManager.GetString("Err00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ईमेल आई.डी पहले से ही दर्ज है।.
        /// </summary>
        internal static string Err00054 {
            get {
                return ResourceManager.GetString("Err00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पासपोर्ट पहले से ही दर्ज है।.
        /// </summary>
        internal static string Err00055 {
            get {
                return ResourceManager.GetString("Err00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ओटीपी को पुनः रिसेट कर दिया गया है।.
        /// </summary>
        internal static string Err00056 {
            get {
                return ResourceManager.GetString("Err00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके मोबाइल नंबर और ईमेल पर ओटीपी भेजा गया है, यह 1 मिनट के लिए वैध है।.
        /// </summary>
        internal static string Err00057 {
            get {
                return ResourceManager.GetString("Err00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आप पहले से ही दूसरे सिस्टम/ब्राउज़र पर लॉगिन है।.
        /// </summary>
        internal static string Err00058 {
            get {
                return ResourceManager.GetString("Err00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एक यूजर एक डिवाइस से अधिक डिवाइस पर लॉगिन नहीं कर सकता है।.
        /// </summary>
        internal static string Err00059 {
            get {
                return ResourceManager.GetString("Err00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to समग्र डाटा प्राप्त  हुआ।.
        /// </summary>
        internal static string Err00060 {
            get {
                return ResourceManager.GetString("Err00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके ईमेल पर ओटीपी भेजा गया है, यह 1 मिनट के लिए वैध है।.
        /// </summary>
        internal static string Err00061 {
            get {
                return ResourceManager.GetString("Err00061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके मोबाइल नंबर पर ओटीपी भेजा गया है, यह 1 मिनट के लिए वैध है।.
        /// </summary>
        internal static string Err00062 {
            get {
                return ResourceManager.GetString("Err00062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपा वैध ओटीपी दर्ज करें।.
        /// </summary>
        internal static string Err00063 {
            get {
                return ResourceManager.GetString("Err00063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्मचारी का पंजीकरण सफलतापूर्वक हो गया है |.
        /// </summary>
        internal static string Err00064 {
            get {
                return ResourceManager.GetString("Err00064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यूज़रनेम और पासवर्ड मेल नहीं खाते हैं। कृपया सही प्रमाण दर्ज करें।!.
        /// </summary>
        internal static string Err00065 {
            get {
                return ResourceManager.GetString("Err00065", resourceCulture);
            }
        }
    }
}
