//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capex.Utilities.Resource.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capex.Utilities.Resource.ErrorMessages.ErrorMessages_en", typeof(ErrorMessages_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hereby declare that I am required to authenticate myself with the Aadhaar based authentication system on the Samagra Portal and provide my Aadhaar number, biometric, and/or One-Time PIN (OTP) data after Aadhaar based authentication. There is no objection in giving consent. I also agree that Samagra Social Security Mission can use my Aadhaar number to establish and authenticate my identity.I hereby consent to sharing my Aadhaar e-KYC details with other State or Central Government departments only for the p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdharDisclosure {
            get {
                return ResourceManager.GetString("AdharDisclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Err00000 {
            get {
                return ResourceManager.GetString("Err00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some technical problem! Please try again!.
        /// </summary>
        internal static string Err00001 {
            get {
                return ResourceManager.GetString("Err00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password..
        /// </summary>
        internal static string Err00002 {
            get {
                return ResourceManager.GetString("Err00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile number..
        /// </summary>
        internal static string Err00003 {
            get {
                return ResourceManager.GetString("Err00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirmed password did not match..
        /// </summary>
        internal static string Err00004 {
            get {
                return ResourceManager.GetString("Err00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password and the new password should not be the same..
        /// </summary>
        internal static string Err00005 {
            get {
                return ResourceManager.GetString("Err00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password did not match..
        /// </summary>
        internal static string Err00006 {
            get {
                return ResourceManager.GetString("Err00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password should not be the same as the old password..
        /// </summary>
        internal static string Err00007 {
            get {
                return ResourceManager.GetString("Err00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully..
        /// </summary>
        internal static string Err00008 {
            get {
                return ResourceManager.GetString("Err00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved successfully..
        /// </summary>
        internal static string Err00009 {
            get {
                return ResourceManager.GetString("Err00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user ID and password..
        /// </summary>
        internal static string Err00010 {
            get {
                return ResourceManager.GetString("Err00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name already exists..
        /// </summary>
        internal static string Err00011 {
            get {
                return ResourceManager.GetString("Err00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role and menu permission saved successfully..
        /// </summary>
        internal static string Err00012 {
            get {
                return ResourceManager.GetString("Err00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role and menu permissions updated successfully..
        /// </summary>
        internal static string Err00013 {
            get {
                return ResourceManager.GetString("Err00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops Something went wrong..
        /// </summary>
        internal static string Err00014 {
            get {
                return ResourceManager.GetString("Err00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name already exists in activated or deactivated records..
        /// </summary>
        internal static string Err00015 {
            get {
                return ResourceManager.GetString("Err00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been sent successfully..
        /// </summary>
        internal static string Err00016 {
            get {
                return ResourceManager.GetString("Err00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in..
        /// </summary>
        internal static string Err00017 {
            get {
                return ResourceManager.GetString("Err00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been successfully deactivated..
        /// </summary>
        internal static string Err00018 {
            get {
                return ResourceManager.GetString("Err00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user ID..
        /// </summary>
        internal static string Err00020 {
            get {
                return ResourceManager.GetString("Err00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role has been successfully deactivated..
        /// </summary>
        internal static string Err00021 {
            get {
                return ResourceManager.GetString("Err00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role has been successfully activated..
        /// </summary>
        internal static string Err00022 {
            get {
                return ResourceManager.GetString("Err00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am unable. To load captcha..
        /// </summary>
        internal static string Err00023 {
            get {
                return ResourceManager.GetString("Err00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha validation has been done successfully..
        /// </summary>
        internal static string Err00024 {
            get {
                return ResourceManager.GetString("Err00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha validation failed..
        /// </summary>
        internal static string Err00025 {
            get {
                return ResourceManager.GetString("Err00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Verification Field..
        /// </summary>
        internal static string Err00026 {
            get {
                return ResourceManager.GetString("Err00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is already activated in the record..
        /// </summary>
        internal static string Err00027 {
            get {
                return ResourceManager.GetString("Err00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samagra ID has been successfully authenticated..
        /// </summary>
        internal static string Err00028 {
            get {
                return ResourceManager.GetString("Err00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been successfully registered. User ID and password have been sent to your email/mobile.
        /// </summary>
        internal static string Err00029 {
            get {
                return ResourceManager.GetString("Err00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete data not received..
        /// </summary>
        internal static string Err00030 {
            get {
                return ResourceManager.GetString("Err00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office save successfully..
        /// </summary>
        internal static string Err00031 {
            get {
                return ResourceManager.GetString("Err00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office update completed successfully..
        /// </summary>
        internal static string Err00032 {
            get {
                return ResourceManager.GetString("Err00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office name exists in records..
        /// </summary>
        internal static string Err00033 {
            get {
                return ResourceManager.GetString("Err00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email ID is already entered. Please provide another email ID..
        /// </summary>
        internal static string Err00034 {
            get {
                return ResourceManager.GetString("Err00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed..
        /// </summary>
        internal static string Err00035 {
            get {
                return ResourceManager.GetString("Err00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully!.
        /// </summary>
        internal static string Err00036 {
            get {
                return ResourceManager.GetString("Err00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID and employee code is already entered..
        /// </summary>
        internal static string Err00038 {
            get {
                return ResourceManager.GetString("Err00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee has joined successfully..
        /// </summary>
        internal static string Err00039 {
            get {
                return ResourceManager.GetString("Err00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not received..
        /// </summary>
        internal static string Err00040 {
            get {
                return ResourceManager.GetString("Err00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change successful..
        /// </summary>
        internal static string Err00041 {
            get {
                return ResourceManager.GetString("Err00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jurisdiction saved successfully..
        /// </summary>
        internal static string Err00042 {
            get {
                return ResourceManager.GetString("Err00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jurisdiction saved successfully..
        /// </summary>
        internal static string Err00043 {
            get {
                return ResourceManager.GetString("Err00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already registered..
        /// </summary>
        internal static string Err00044 {
            get {
                return ResourceManager.GetString("Err00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is already entered..
        /// </summary>
        internal static string Err00045 {
            get {
                return ResourceManager.GetString("Err00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jurisdiction update completed successfully..
        /// </summary>
        internal static string Err00046 {
            get {
                return ResourceManager.GetString("Err00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deactivated successfully..
        /// </summary>
        internal static string Err00047 {
            get {
                return ResourceManager.GetString("Err00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-KYC is not updated. Please update your e-KYC on Samagra portal. Then after that create your account..
        /// </summary>
        internal static string Err00048 {
            get {
                return ResourceManager.GetString("Err00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is not updated on Samagra portal..
        /// </summary>
        internal static string Err00049 {
            get {
                return ResourceManager.GetString("Err00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully. User ID and password have been sent to your email/mobile.
        /// </summary>
        internal static string Err00050 {
            get {
                return ResourceManager.GetString("Err00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N-R-I details updated successfully..
        /// </summary>
        internal static string Err00051 {
            get {
                return ResourceManager.GetString("Err00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP verified successfully..
        /// </summary>
        internal static string Err00052 {
            get {
                return ResourceManager.GetString("Err00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid OTP..
        /// </summary>
        internal static string Err00053 {
            get {
                return ResourceManager.GetString("Err00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID is already entered..
        /// </summary>
        internal static string Err00054 {
            get {
                return ResourceManager.GetString("Err00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport already registered..
        /// </summary>
        internal static string Err00055 {
            get {
                return ResourceManager.GetString("Err00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP has been reset..
        /// </summary>
        internal static string Err00056 {
            get {
                return ResourceManager.GetString("Err00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been sent to your mobile number and email, it is valid for 1 minute..
        /// </summary>
        internal static string Err00057 {
            get {
                return ResourceManager.GetString("Err00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in to another system/browser..
        /// </summary>
        internal static string Err00058 {
            get {
                return ResourceManager.GetString("Err00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user cannot login on more than one device..
        /// </summary>
        internal static string Err00059 {
            get {
                return ResourceManager.GetString("Err00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete data received..
        /// </summary>
        internal static string Err00060 {
            get {
                return ResourceManager.GetString("Err00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been sent to your email, it is valid for 1 minute..
        /// </summary>
        internal static string Err00061 {
            get {
                return ResourceManager.GetString("Err00061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been sent to your mobile number, it is valid for 1 minute..
        /// </summary>
        internal static string Err00062 {
            get {
                return ResourceManager.GetString("Err00062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid OTP..
        /// </summary>
        internal static string Err00063 {
            get {
                return ResourceManager.GetString("Err00063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee registration has been done successfully..
        /// </summary>
        internal static string Err00064 {
            get {
                return ResourceManager.GetString("Err00064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password do not match. Please enter correct credentials..
        /// </summary>
        internal static string Err0065 {
            get {
                return ResourceManager.GetString("Err0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId already exists in records.
        /// </summary>
        internal static string UserIdExists {
            get {
                return ResourceManager.GetString("UserIdExists", resourceCulture);
            }
        }
    }
}
