<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Capex.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Common\Controllers\CaptchaController.cs" />
    <Compile Remove="Areas\Common\Controllers\CitizenController.cs" />
    <Compile Remove="Areas\Common\Controllers\MessageNotificationController.cs" />
    <Compile Remove="Areas\Common\Controllers\SSOLoginController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.0" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="7.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.16" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RedirectAndPostCore" Version="1.0.2" />
    <PackageReference Include="Serilog" Version="3.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
    <PackageReference Include="SimpleInjector.Integration.AspNetCore.Mvc.Core" Version="5.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Common\Data\" />
    <Folder Include="Areas\Common\Models\" />
    <Folder Include="Areas\Common\Views\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Capex.Business\Capex.Business.csproj" />
    <ProjectReference Include="..\Capex.DomainModels\Capex.DomainModels.csproj" />
    <ProjectReference Include="..\Capex.Infrastructure\Capex.Infrastructure.csproj" />
    <ProjectReference Include="..\Capex.Models\Capex.Models.csproj" />
    <ProjectReference Include="..\Capex.Utilities\Capex.Utilities.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties connectionstrings_1json__JsonSchema="https://carafe.fm/schema/draft-02/bundle.schema.json" /></VisualStudio></ProjectExtensions>

</Project>
